export const MyTeam = [
  {
    teamId: "001",
    name: "自チーム",
    players: [
      {playerId: 1, num: 1, name: "澤村大地", nickname: "大地"},
      {playerId: 2, num: 3, name: "東峰旭", nickname: "旭"},
      {playerId: 3, num: 5, name: "田中龍之介", nickname: "田中"},
      {playerId: 4, num: 9, name: "影山飛雄", nickname: "影山"},
      {playerId: 5, num: 10, name: "日向翔陽", nickname: "日向"},
      {playerId: 6, num: 11, name: "月島蛍", nickname: "月島"},
      {playerId: 7, num: 4, name: "西谷夕", nickname: "西谷"},
      {PlayerId: 8, num: 43, name: "高橋黎", nickname: "れい"},
    ],
    match: [
      {matchId: 1}
    ]
  }
]

// 自チームの選手データ
export const Players = [
{
  id: 1,
  num: 1,
  name: "澤村大地",
  nickname: "澤村",
  spike: [],
  score: [],
},
{
  id: 2,
  num: 3,
  name: "東峰旭",
  nickname: "旭",
  spike: [],
  score: [],
},
{
  id: 3,
  num: 5,
  name: "田中龍之介",
  nickname: "田中",
  spike: [],
  score: [],
},
{
  id: 4,
  num: 9,
  name: "影山飛雄",
  nickname: "影山",
  spike: [],
  score: [],
},
{
  id: 5,
  num: 10,
  name: "日向翔陽",
  nickname: "日向",
  spike: [],
  score: [],
},
{
  id: 6,
  num: 11,
  name: "月島蛍",
  nickname: "月島",
  spike: [],
  score: [],
},
{
  id: 7,
  num: 4,
  name: "西谷夕",
  nickname: "西谷",
  spike: [],
  score: [],
},
{
  id: 8,
  num: 43,
  name: "高橋黎",
  nickname: "れい",
  spike: [],
  score: [],
},
];

// チームデータ
export const Opponents = [
{
  value: "001",
  name: "北海道教育大学",
  label: "教育大",
},
{
  value: "002",
  name: "酒田東高校",
  label: "酒東",
},
{
  value: "003",
  name: "山形第六中",
  label: "六中",
},
{
  value: "004",
  name: "烏野高校",
  label: "烏野",
},
];

// 試合データ
export const Matches = [
{
  matchId : 1,
  date : "2024-02-28",
  opponentTeams : "001",
  sets : [
    {setId : 1, 
      actions: [
        {
          id: 1,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 2,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 3,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 4,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 5,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 6,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 7,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 8,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 9,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 10,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 11,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 12,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 13,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 14,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 15,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 16,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 17,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 18,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 19,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 20,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 21,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 22,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 23,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 24,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 25,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 26,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 27,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 28,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 29,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 30,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 31,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 32,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 33,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 34,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 35,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 36,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 37,
          playerId: 1,
          serve: "エース",
          isAce: true,
          isMiss: false,
          reason: {value: null, playerId: 1},
          score: {my: 0, opponent: 0},
        },
        {
          id: 38,
          playerId: 1,
          serve: "ミス",
          isAce: false,
          isMiss: true,
          reason: {value: null, playerId: null},
          score: {my: 0, opponent: 0},
        },
        {
          id: 39,
          playerId: null,
          serve: null,
          isAce: false,
          isMiss: false,
          reason: {value: "スパイク", playerId: 1},
          score: {my: 0, opponent: 0},
        },
      ],
    },
  ],
  starPlayer: [
    {playerId: 1},
    {playerId: 2},
    {playerId: 3},
    {playerId: 4},
    {playerId: 5},
    {playerId: 6},
    {playerId: 7},
  ],
  benchMem: [
    {playerId: 8},
  ],
  reception : [
    {receptionId: "A", receptionNum: 1},
    {receptionId: "B", receptionNum: 2},
    {receptionId: "C", receptionNum: 4},
    {receptionId: "D", receptionNum: 0},
  ],
  spike : [
    {playerId: 1, spikeScore: 5},
    {playerId: 2, spikeScore: 4},
    {playerId: 3, spikeScore: 2},
    {playerId: 4, spikeScore: 1},
    {playerId: 5, spikeScore: 0},
  ],
},
]


// {
//   matchId : "2",
//   date : "2024-02-28",
//   opponentTeams : "004",
//   sets : [
//     {setNumber : 1, myTeamScore : 25, opponentTeamScore : 20},
//     {setNumber : 2, myTeamScore : 25, opponentTeamScore : 20},
//   ],
//   starPlayer: [
//     {playerId: 1},
//     {playerId: 2},
//     {playerId: 3},
//     {playerId: 4},
//     {playerId: 5},
//     {playerId: 6},
//     {playerId: 7},
//   ],
//   benchMem: [
//     {PlayerId: 8},
//   ],
//   reception : [
//     {receptionId: "A", receptionNum: 1},
//     {receptionId: "B", receptionNum: 2},
//     {receptionId: "C", receptionNum: 4},
//     {receptionId: "D", receptionNum: 0},
//   ],
//   spike : [
//     {playerId: 1, spikeScore: 5},
//     {playerId: 2, spikeScore: 4},
//     {playerId: 3, spikeScore: 2},
//     {playerId: 4, spikeScore: 1},
//     {playerId: 5, spikeScore: 0},
//   ],
// },





export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "イケメンれいさん",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "なぎ",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "おちん",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "はるちゃ",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "ランちゃん",
  },
];
